/**
 * @Project Name: Room Management System.
 * @Package Code: urm
 * @Date Project Started: October 1st, 2013
 * @Date Implementation started: November 13th, 2013
 * @Description: The users of the system will be able to login and the user will be able to reserve 
 * a room and delete your room reservation.
 *
 * @author: Sean Morgan
 */
package urm;

/**
 * @Class FrmMenu: This is the main menu of the system. It allows you to choose what function you
 * want. It will take you to the reserve a room screen, and view reservations screen where you can
 * view your reservations and if necessary delete a reservation. It the user is the administrator
 * than they could go and view all the reservations and the available building and room numbers and
 * what type of room it is.
 *
 * @author Sean
 */
public class FrmMenu extends javax.swing.JFrame {

   private String userName;
   private FrmLogin frmLogin;
   private FrmReservations frmReservations;
   private FrmViewUReservations frmViewUReservations;
   private FrmReserveRoom frmReserveRoom;

   /**
    * Creates new form Menu
    */
   public FrmMenu() {
      initComponents();

   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jMenuItem1 = new javax.swing.JMenuItem();
      jMenu1 = new javax.swing.JMenu();
      btnviewAllReservations = new javax.swing.JButton();
      btnReserveARoom = new javax.swing.JButton();
      btnViewUReservations = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      btnLogout = new javax.swing.JButton();
      lblUser = new javax.swing.JLabel();
      jMenuBar1 = new javax.swing.JMenuBar();
      MListFile = new javax.swing.JMenu();
      mbnLogout = new javax.swing.JMenuItem();
      jSeparator1 = new javax.swing.JPopupMenu.Separator();
      mbnExit = new javax.swing.JMenuItem();
      mListView = new javax.swing.JMenu();
      mbnReserveRoom = new javax.swing.JMenuItem();
      mbnYouReservations = new javax.swing.JMenuItem();

      jMenuItem1.setText("jMenuItem1");

      jMenu1.setText("jMenu1");

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Room Managment System");
      setPreferredSize(new java.awt.Dimension(500, 500));

      btnviewAllReservations.setText("View All Reservations");
      btnviewAllReservations.setMaximumSize(new java.awt.Dimension(150, 50));
      btnviewAllReservations.setMinimumSize(new java.awt.Dimension(150, 50));
      btnviewAllReservations.setPreferredSize(new java.awt.Dimension(150, 50));
      btnviewAllReservations.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnviewAllReservationsActionPerformed(evt);
         }
      });

      btnReserveARoom.setText("Reserve a Room");
      btnReserveARoom.setMaximumSize(new java.awt.Dimension(150, 50));
      btnReserveARoom.setMinimumSize(new java.awt.Dimension(150, 50));
      btnReserveARoom.setPreferredSize(new java.awt.Dimension(150, 50));
      btnReserveARoom.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnReserveARoomActionPerformed(evt);
         }
      });

      btnViewUReservations.setText("View Your Reservations");
      btnViewUReservations.setMaximumSize(new java.awt.Dimension(150, 50));
      btnViewUReservations.setMinimumSize(new java.awt.Dimension(150, 50));
      btnViewUReservations.setPreferredSize(new java.awt.Dimension(150, 50));
      btnViewUReservations.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnViewUReservationsActionPerformed(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel1.setText("Room Registration System");

      btnLogout.setLabel("Logout");
      btnLogout.setMaximumSize(new java.awt.Dimension(150, 50));
      btnLogout.setMinimumSize(new java.awt.Dimension(150, 50));
      btnLogout.setPreferredSize(new java.awt.Dimension(150, 50));
      btnLogout.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLogoutActionPerformed(evt);
         }
      });

      lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

      MListFile.setText("File");

      mbnLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
      mbnLogout.setText("Logout");
      mbnLogout.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            mbnLogoutActionPerformed(evt);
         }
      });
      MListFile.add(mbnLogout);
      MListFile.add(jSeparator1);

      mbnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
      mbnExit.setText("Exit");
      mbnExit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            mbnExitActionPerformed(evt);
         }
      });
      MListFile.add(mbnExit);

      jMenuBar1.add(MListFile);

      mListView.setActionCommand("View");
      mListView.setLabel("View");

      mbnReserveRoom.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
      mbnReserveRoom.setText("Reserve Room");
      mListView.add(mbnReserveRoom);

      mbnYouReservations.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
      mbnYouReservations.setText("Your Reservations");
      mListView.add(mbnYouReservations);

      jMenuBar1.add(mListView);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
               .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addGap(94, 94, 94)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(btnReserveARoom, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
               .addComponent(btnViewUReservations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnviewAllReservations, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(94, 94, 94))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(45, 45, 45)
            .addComponent(btnReserveARoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(13, 13, 13)
            .addComponent(btnViewUReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(13, 13, 13)
            .addComponent(btnviewAllReservations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(13, 13, 13)
            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(45, 45, 45))
      );

      pack();
      setLocationRelativeTo(null);
   }// </editor-fold>//GEN-END:initComponents
   /**
    * @Method: btnviewAllReservationsActionPerformed
    * @Detail: This shows the administrator form.
    * @param evt
    */
    private void btnviewAllReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewAllReservationsActionPerformed
       frmReservations = new FrmReservations();
       frmReservations.getCreds(userName, this);
       frmReservations.pack();
       frmReservations.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnviewAllReservationsActionPerformed
   /**
    * @Method:btnReserveARoomActionPerformed
    * @Detail: This shows the reserve a room form.
    * @param evt
    */
    private void btnReserveARoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveARoomActionPerformed
       frmReserveRoom = new FrmReserveRoom();
       frmReserveRoom.pack();
       frmReserveRoom.getCreds(userName, this);
       frmReserveRoom.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnReserveARoomActionPerformed
   /**
    * @Method: btnViewUReservationsActionPerformed
    * @Detail: Show the current users reservations form.
    * @param evt
    */
    private void btnViewUReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUReservationsActionPerformed
       frmViewUReservations = new FrmViewUReservations();
       frmViewUReservations.pack();
       frmViewUReservations.getCreds(userName, this);
       frmViewUReservations.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnViewUReservationsActionPerformed
   /**
    * @Method: btnLogoutActionPerformed
    * @Detail: This Logs out the current user and shows the login screen
    * @param evt
    */
   private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      userName = "";
      this.setVisible(false);
      frmLogin.clearUser();
      frmLogin.setVisible(true);
   }//GEN-LAST:event_btnLogoutActionPerformed
   /**
    * @Method: mbnExitActionPerformed
    * @Detail: Closes the application
    * @param evt
    */
   private void mbnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbnExitActionPerformed
      System.exit(0);
   }//GEN-LAST:event_mbnExitActionPerformed
   /**
    * @Method: mbnLogoutActionPerformed
    * @Detail: calls the Logout function "btnLogoutActionPerformed"
    * @param evt
    */
   private void mbnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbnLogoutActionPerformed
      btnLogoutActionPerformed(evt);
   }//GEN-LAST:event_mbnLogoutActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>
        /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new FrmMenu().setVisible(true);
         }
      });
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenu MListFile;
   private javax.swing.JButton btnLogout;
   private javax.swing.JButton btnReserveARoom;
   private javax.swing.JButton btnViewUReservations;
   private javax.swing.JButton btnviewAllReservations;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JPopupMenu.Separator jSeparator1;
   private javax.swing.JLabel lblUser;
   private javax.swing.JMenu mListView;
   private javax.swing.JMenuItem mbnExit;
   private javax.swing.JMenuItem mbnLogout;
   private javax.swing.JMenuItem mbnReserveRoom;
   private javax.swing.JMenuItem mbnYouReservations;
   // End of variables declaration//GEN-END:variables
   /**
    * @Method: IsAdmin
    * @Detail: Sets the current user to have administrator privileges
    */
   public void IsAdmin() {
      btnviewAllReservations.setVisible(true);
   }
   /**
    * @Method: IsUser
    * @Detail: Sets the current user as standard user
    */
   public void IsUser() {
      btnviewAllReservations.setVisible(false);
   }
   /**
    * @Method: getCreds
    * @Detail: This passes the vital information from the login screen
    * @param inUserName
    * @param inFrmLogin
    */
   public void getCreds(String inUserName, FrmLogin inFrmLogin) {
      userName = inUserName;
      frmLogin = inFrmLogin;
   }
}
